# Generated by Django 5.0.6 on 2024-06-28 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='veiculo',
            old_name='nome',
            new_name='marca',
        ),
        migrations.AddField(
            model_name='veiculo',
            name='motorista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.motorista'),
        ),
    ]
